// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Geyser = (function(_super) {

    __extends(Geyser, _super);

    function Geyser() {
      return Geyser.__super__.constructor.apply(this, arguments);
    }

    Geyser.prototype.firebaseRef = 'https://geyser.firebaseio.com/';

    Geyser.prototype.initialize = function(options) {
      var _this = this;
      this.options = options;
      this.reader = new FileReader();
      this.reader.onload = function(file) {
        var f;
        f = new Firebase(_this.firebaseRef + 'users/fred/captures/filePayload');
        return f.set(file.target.result, function() {
          return console.log('saved to firebase');
        });
      };
      return this.savePage();
    };

    Geyser.prototype.savePage = function() {
      var _this = this;
      return chrome.tabs.getSelected(null, function(tab) {
        return chrome.pageCapture.saveAsMHTML({
          tabId: tab.id
        }, function(mhtml) {
          return _this.reader.readAsDataURL(mhtml);
        });
      });
    };

    return Geyser;

  })(Backbone.View);

}).call(this);
